### ISSUE TITLE
ci/cd 툴 자료조사

### ISSUE THREAD

**Issue by MojitoBar** [My-Pack/MyPack-iOS#2]

**Comment by MojitoBar** [comment]
https://munokkim.medium.com/github-actions-fastlane%EC%9C%BC%EB%A1%9C-%EC%95%B1-%EB%B0%B0%ED%8F%AC-%EC%9E%90%EB%8F%99%ED%99%94%ED%95%98%EA%B8%B0-5a420493e978

**Comment by hanni66** [comment]
### CI/CD
- 테스트 하는 과정이 테스트 코드와 무슨 차이가 있나?
    - 테스트 코드는 개발단에서 기능별 테스트를 진행, CI의 테스트는 작성된 모든 코드를 테스트함.
- Validation & compliance 는 개발단에서 진행하는 것인가?
    - 배포까지만 진행하니 Validation & compliance 단계는 일단 패스한다.

### 진행 방식
- CI
  - lint - build - test 순서로 진행한다.
- CD
  - testflight, appstore 2개로 진행
  - [Fastlane을 이용한 배포 자동화](https://munokkim.medium.com/github-actions-fastlane%EC%9C%BC%EB%A1%9C-%EC%95%B1-%EB%B0%B0%ED%8F%AC-%EC%9E%90%EB%8F%99%ED%99%94%ED%95%98%EA%B8%B0-5a420493e978)
