### ISSUE TITLE
test code 단위 정하기

### ISSUE THREAD

**Issue by hanni66** [My-Pack/MyPack-iOS#3]

**Comment by MojitoBar** [comment]
### UI TEST
https://www.youtube.com/watch?v=ECuc3qoRm90

**Comment by hanni66** [comment]
Test code
- Test First : 테스트를 먼저 작성한다.
- UI test : https://www.youtube.com/watch?v=ECuc3qoRm90
- Unit test : Code coverage 를 100%가 되는 것을 목표로 한다.
