### ISSUE TITLE
라벨링 정하기

### ISSUE THREAD

**Issue by hanni66** [My-Pack/MyPack-iOS#4]

**Comment by MojitoBar** [comment]
### 확정 라벨링
🚨 HotFix : 급하게 merge 해야하는 경우 (코드 리뷰는 필수)
✍️ Review: 리뷰를 진행해도 되는 경우
🛠 Working: 작업 중인 경우
🫠 Low: 중요도가 낮은 문제 (리뷰 안해도 됨, 간단한 문서 작업 혹은 간단한 스타일 변경 등)

### PR title prefix
💛 Feature : 기능 개발
🚑 Fix: 기능 수정 & 변경 (문제가 있을 때를 가정)
📄 Docs : 문서 작성 및 수정
🧩 Refactor : 리팩토링 (문제는 없지만 코드 품질을 위한 수정)
✅ Test : 테스트 코드 관련

### branch 네이밍 규칙
Feature/main-view-ui
Feature/login-view-button-style
Test/login-api-test-code

### 커밋 컨벤션
[#이슈번호] 한글로 핵심만 간단히 (바로 알아볼 수 있게)
[#10] 로그인 API 연결
