### ISSUE TITLE
MVVM 패턴 자료 조사하기

### ISSUE THREAD

**Issue by MojitoBar** [My-Pack/MyPack-iOS#5]

**Comment by MojitoBar** [comment]
https://beomy.tistory.com/43

**Comment by hanni66** [comment]
### MVC
- Controller 에서 action을 받는다.
- controller에서 요청된 model로 바뀐 것을 controller가 view로 보내준다.
- view가 받으려면 model을 알고 있어야한다.

### MVVM
- 데이터 바인딩이라는 개념을 잘 알고 있어야한다.
- View 에서 action을 받는다.
- VM에서 model을 사용 (모델은 그냥 형체(?) 같은 것)
- view랑 viewModel은 바인딩 되어 있다.
- view는 model을 몰라도 된다.
